const mongoose = require('mongoose');

const VALID_MBTI = [
  'INTJ','INTP','ENTJ','ENTP',
  'INFJ','INFP','ENFJ','ENFP',
  'ISTJ','ISFJ','ESTJ','ESFJ',
  'ISTP','ISFP','ESTP','ESFP',
];

const UserSchema = new mongoose.Schema(
  {
    // UUID generated by client on first visit; stored in localStorage.
    // Used as a lightweight identity without full auth for MVP.
    clientId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },

    // Short-form MBTI from 4-question forced-choice capture
    mbtiType: {
      type: String,
      enum: [...VALID_MBTI, null],
      default: null,
    },

    // IANA timezone string (e.g. "Asia/Kolkata")
    timezone: { type: String, default: null },

    // Last known browser or IP-fallback coordinates
    lastKnownLatLong: {
      lat: { type: Number, default: null },
      lng: { type: Number, default: null },
    },

    /**
     * Vedic birth chart — FEATURE FLAGGED (ASTRO_ENABLED).
     * Sub-document is optional; used only for secondary re-rank layer.
     * Do NOT use as a filter. Source: fed in from external calculator.
     *
     * TODO (Post-MVP): Connect to Vedic chart input flow once
     * astrology feature flag is enabled.
     */
    birthChart: {
      moonSign: { type: String, default: null },  // e.g. "Vrishchika"
      nakshatra: { type: String, default: null },  // e.g. "Anuradha"
      lagna:     { type: String, default: null },  // Ascendant sign
    },

    // Lightweight listening history for future personalisation (not used in MVP ranking)
    listeningHistory: [
      {
        ragaId:     { type: mongoose.Schema.Types.ObjectId, ref: 'Raga' },
        listenedAt: { type: Date, default: Date.now },
      },
    ],
  },
  { timestamps: true }
);

module.exports = mongoose.model('User', UserSchema);
